
["Quarrying and Mining Options"]
	#Disable silktouch enchantment on geo-stone blocks? Forces needing the quarrying chisel - Default true
	disableSilktouch = true
	#Disable fortune enchantment on geo-stone blocks? Default - false
	disableFortune = false

["Stone Property Options"]
	#depth multiplier, recommended 20, 1 to disable
	#Range: 1 ~ 2
	stoneDepthMultiplier = 1
	#depth multiplier start, recommended y=50
	#Range: 0 ~ 65535
	stoneDepthMultiplierStart = 50
	#hardness multiplier, set to 1 to disable
	#Range: 1 ~ 2
	stoneHardnessMultiplier = 1

["Debug Options"]
	#Debug ore-type registration methods/API - Default false
	debugOreRegistry = true

