
["Vanilla World-Gen Options"]
	#No comment
	disableMineshafts = true
	#No comment
	disableWaterLakes = true
	#No comment
	disableLavaSprings = true
	#No comment
	disableLavaLakes = true
	#No comment
	disableWaterSprings = true
	#No comment
	disableFossils = true

["Quarrying and Mining Options"]
	#Disable silktouch enchantment on geo-stone blocks? Forces needing a quarrying tool - Default true
	disableSilktouch = true
	#Disable fortune enchantment on geo-stone blocks? Default - false
	disableFortune = false

["Stone Property Options"]
	#depth multiplier, recommended 20, 1 to disable
	#Range: 1 ~ 2
	stoneDepthMultiplier = 1
	#depth multiplier start, recommended y=50
	#Range: 0 ~ 65535
	stoneDepthMultiplierStart = 50
	#hardness multiplier, set to 1 to disable
	#Range: 1 ~ 2
	stoneHardnessMultiplier = 1

["Debug Options"]
	#Debug ore-type registration methods/API - Default false
	debugOreRegistry = true
	#Debug the biome vanilla feature remover - Default false
	debugFeatureRemover = false
	#Debug the boulder feature when placing - Default false
	debugBoulderFeature = true

